<?php

use Illuminate\Database\Seeder;
use App\Permission;

class RolePermissionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $actions = [
           
            ['id' => 1,'module' => 'role','sub_module' => 'role','name' => 'role-list','guard_name' => 'admin',],
            ['id' => 2,'module' => 'role','sub_module' => 'role','name' => 'role-create','guard_name' => 'admin',],
            ['id' => 3,'module' => 'role','sub_module' => 'role','name' => 'role-edit','guard_name' => 'admin',],
            ['id' => 4,'module' => 'role','sub_module' => 'role','name' => 'role-delete','guard_name' => 'admin',],
            ['id' => 5,'module' => 'overview','sub_module' => 'overview','name' => 'overview-transaction-statistics','guard_name' => 'admin',],
            ['id' => 6,'module' => 'overview','sub_module' => 'overview','name' => 'overview-latest-transactions','guard_name' => 'admin',],
            ['id' => 7,'module' => 'overview','sub_module' => 'overview','name' => 'overview-latest-tickets','guard_name' => 'admin',],
            ['id' => 8,'module' => 'overview','sub_module' => 'overview','name' => 'overview-latest-refunds','guard_name' => 'admin',],
            ['id' => 9,'module' => 'overview','sub_module' => 'overview','name' => 'overview-latest-chargebacks','guard_name' => 'admin',],
            ['id' => 10,'module' => 'overview','sub_module' => 'overview','name' => 'overview-latest-suspicious-transaction','guard_name' => 'admin',],
            ['id' => 16,'module' => 'users','sub_module' => 'user admin','name' => 'users-admin-list','guard_name' => 'admin',],
            ['id' => 17,'module' => 'users','sub_module' => 'user admin','name' => 'create-admin','guard_name' => 'admin',],
            ['id' => 18,'module' => 'users','sub_module' => 'user admin','name' => 'update-admin','guard_name' => 'admin',],
            ['id' => 19,'module' => 'users','sub_module' => 'user admin','name' => 'view-admin','guard_name' => 'admin',],
            ['id' => 20,'module' => 'users','sub_module' => 'user admin','name' => 'delete-admin','guard_name' => 'admin',],
            ['id' => 21,'module' => 'users','sub_module' => 'user agent','name' => 'users-agents-list','guard_name' => 'admin',],
            ['id' => 22,'module' => 'users','sub_module' => 'user agent','name' => 'create-agent','guard_name' => 'admin',],
            ['id' => 23,'module' => 'users','sub_module' => 'user agent','name' => 'view-agent','guard_name' => 'admin',],
            ['id' => 24,'module' => 'users','sub_module' => 'user agent','name' => 'update-agent','guard_name' => 'admin',],
            ['id' => 25,'module' => 'users','sub_module' => 'user agent','name' => 'delete-agent','guard_name' => 'admin',],
            ['id' => 26,'module' => 'users','sub_module' => 'user agent','name' => 'can-delegate-access-agent','guard_name' => 'admin',],
            ['id' => 27,'module' => 'users','sub_module' => 'user merchant','name' => 'create-merchant','guard_name' => 'admin',],
            ['id' => 28,'module' => 'users','sub_module' => 'user merchant','name' => 'view-merchant','guard_name' => 'admin',],
            ['id' => 29,'module' => 'users','sub_module' => 'user merchant','name' => 'update-merchant','guard_name' => 'admin',],
            ['id' => 30,'module' => 'users','sub_module' => 'user merchant','name' => 'delete-merchant','guard_name' => 'admin',],
            ['id' => 31,'module' => 'users','sub_module' => 'user merchant','name' => 'export-merchant','guard_name' => 'admin',],
            ['id' => 32,'module' => 'users','sub_module' => 'user merchant','name' => 'send-mail-to-merchant','guard_name' => 'admin',],
            ['id' => 33,'module' => 'users','sub_module' => 'user merchant','name' => 'sub-users-list','guard_name' => 'admin',],
            ['id' => 34,'module' => 'users','sub_module' => 'sub user','name' => 'list-sub-user','guard_name' => 'admin',],
            ['id' => 35,'module' => 'users','sub_module' => 'sub user','name' => 'update-sub-user','guard_name' => 'admin',],
            ['id' => 36,'module' => 'users','sub_module' => 'sub user','name' => 'delete-sub-user','guard_name' => 'admin',],
            ['id' => 37,'module' => 'mid','sub_module' => 'gateway management','name' => 'create-gateway','guard_name' => 'admin',],
            ['id' => 38,'module' => 'mid','sub_module' => 'gateway management','name' => 'list-gateway','guard_name' => 'admin',],
            ['id' => 39,'module' => 'mid','sub_module' => 'gateway management','name' => 'update-gateway','guard_name' => 'admin',],
            ['id' => 41,'module' => 'mid','sub_module' => 'gateway management','name' => 'create-sub-gateway','guard_name' => 'admin',],
            ['id' => 42,'module' => 'mid','sub_module' => 'gateway management','name' => 'list-sub-gateway','guard_name' => 'admin',],
            ['id' => 43,'module' => 'mid','sub_module' => 'gateway management','name' => 'update-sub-gateway','guard_name' => 'admin',],
            ['id' => 44,'module' => 'mid','sub_module' => 'gateway management','name' => 'delete-sub-gateway','guard_name' => 'admin',],
            ['id' => 45,'module' => 'mid','sub_module' => 'mid','name' => 'list-mid','guard_name' => 'admin',],
            ['id' => 46,'module' => 'mid','sub_module' => 'mid','name' => 'create-mid','guard_name' => 'admin',],
            ['id' => 47,'module' => 'mid','sub_module' => 'mid','name' => 'update-mid','guard_name' => 'admin',],
            ['id' => 48,'module' => 'mid','sub_module' => 'mid','name' => 'delete-mid','guard_name' => 'admin',],
            ['id' => 49,'module' => 'mid','sub_module' => 'mid','name' => 'view-mid','guard_name' => 'admin',],
            ['id' => 50,'module' => 'mid','sub_module' => 'rules','name' => 'list-rule','guard_name' => 'admin',],
            ['id' => 51,'module' => 'mid','sub_module' => 'rules','name' => 'create-rule','guard_name' => 'admin',],
            ['id' => 52,'module' => 'mid','sub_module' => 'rules','name' => 'update-rule','guard_name' => 'admin',],
            ['id' => 53,'module' => 'mid','sub_module' => 'rules','name' => 'delete-rule','guard_name' => 'admin',],
            ['id' => 54,'module' => 'mid','sub_module' => 'rules','name' => 'assign-to-mid','guard_name' => 'admin',],
            ['id' => 55,'module' => 'applications','sub_module' => 'applications','name' => 'list-application','guard_name' => 'admin',],
            ['id' => 56,'module' => 'applications','sub_module' => 'applications','name' => 'update-application','guard_name' => 'admin',],
            ['id' => 57,'module' => 'applications','sub_module' => 'applications','name' => 'delete-application','guard_name' => 'admin',],
            ['id' => 58,'module' => 'applications','sub_module' => 'applications','name' => 'view-application','guard_name' => 'admin',],
            ['id' => 59,'module' => 'applications','sub_module' => 'applications','name' => 'export-application','guard_name' => 'admin',],
            ['id' => 60,'module' => 'applications','sub_module' => 'applications','name' => 'send-email-application','guard_name' => 'admin',],
            ['id' => 61,'module' => 'applications','sub_module' => 'application-complete','name' => 'list-application-complete','guard_name' => 'admin',],
            ['id' => 62,'module' => 'applications','sub_module' => 'application-complete','name' => 'update-application-complete','guard_name' => 'admin',],
            ['id' => 63,'module' => 'applications','sub_module' => 'application-complete','name' => 'delete-application-complete','guard_name' => 'admin',],
            ['id' => 64,'module' => 'applications','sub_module' => 'application-complete','name' => 'view-application-complete','guard_name' => 'admin',],
            ['id' => 65,'module' => 'applications','sub_module' => 'application-complete','name' => 'export-application-complete','guard_name' => 'admin',],
            ['id' => 66,'module' => 'applications','sub_module' => 'application-complete','name' => 'not-interested-application-complete','guard_name' => 'admin',],
            ['id' => 67,'module' => 'applications','sub_module' => 'application-approved','name' => 'list-application-approved','guard_name' => 'admin',],
            ['id' => 68,'module' => 'applications','sub_module' => 'application-approved','name' => 'update-application-approved','guard_name' => 'admin',],
            ['id' => 69,'module' => 'applications','sub_module' => 'application-approved','name' => 'delete-application-approved','guard_name' => 'admin',],
            ['id' => 70,'module' => 'applications','sub_module' => 'application-approved','name' => 'view-application-approved','guard_name' => 'admin',],
            ['id' => 71,'module' => 'applications','sub_module' => 'application-approved','name' => 'export-application-approved','guard_name' => 'admin',],
            ['id' => 72,'module' => 'applications','sub_module' => 'application-approved','name' => 'not-interested-application-approved','guard_name' => 'admin',],
            ['id' => 73,'module' => 'applications','sub_module' => 'application-rejected','name' => 'list-application-rejected','guard_name' => 'admin',],
            ['id' => 74,'module' => 'applications','sub_module' => 'application-rejected','name' => 'restore-application-rejected','guard_name' => 'admin',],
            ['id' => 75,'module' => 'applications','sub_module' => 'application-rejected','name' => 'delete-application-rejected','guard_name' => 'admin',],
            ['id' => 76,'module' => 'applications','sub_module' => 'application-rejected','name' => 'view-application-rejected','guard_name' => 'admin',],
            ['id' => 77,'module' => 'applications','sub_module' => 'application-rejected','name' => 'export-application-rejected','guard_name' => 'admin',],
            ['id' => 78,'module' => 'applications','sub_module' => 'application-not-interested','name' => 'list-application-not-interested','guard_name' => 'admin',],
            ['id' => 79,'module' => 'applications','sub_module' => 'application-not-interested','name' => 'update-application-not-interested','guard_name' => 'admin',],
            ['id' => 80,'module' => 'applications','sub_module' => 'application-not-interested','name' => 'restore-application-not-interested','guard_name' => 'admin',],
            ['id' => 81,'module' => 'applications','sub_module' => 'application-not-interested','name' => 'delete-application-not-interested','guard_name' => 'admin',],
            ['id' => 82,'module' => 'applications','sub_module' => 'application-not-interested','name' => 'view-application-not-interested','guard_name' => 'admin',],
            ['id' => 83,'module' => 'applications','sub_module' => 'application-not-interested','name' => 'export-application-not-interested','guard_name' => 'admin',],
            ['id' => 84,'module' => 'applications','sub_module' => 'application-terminated','name' => 'list-application-terminated','guard_name' => 'admin',],
            ['id' => 85,'module' => 'applications','sub_module' => 'application-terminated','name' => 'delete-application-terminated','guard_name' => 'admin',],
            ['id' => 86,'module' => 'applications','sub_module' => 'application-terminated','name' => 'view-application-terminated','guard_name' => 'admin',],
            ['id' => 87,'module' => 'applications','sub_module' => 'application-terminated','name' => 'export-application-terminated','guard_name' => 'admin',],
            ['id' => 88,'module' => 'applications','sub_module' => 'application-agreement-send','name' => 'list-application-agreement-send','guard_name' => 'admin',],
            ['id' => 89,'module' => 'applications','sub_module' => 'application-agreement-send','name' => 'update-application-agreement-send','guard_name' => 'admin',],
            ['id' => 90,'module' => 'applications','sub_module' => 'application-agreement-send','name' => 'delete-application-agreement-send','guard_name' => 'admin',],
            ['id' => 91,'module' => 'applications','sub_module' => 'application-agreement-send','name' => 'view-application-agreement-send','guard_name' => 'admin',],
            ['id' => 92,'module' => 'applications','sub_module' => 'application-agreement-send','name' => 'export-application-agreement-send','guard_name' => 'admin',],
            ['id' => 93,'module' => 'applications','sub_module' => 'application-agreement-send','name' => 'not-interested-application-agreement-send','guard_name' => 'admin',],
            ['id' => 94,'module' => 'applications','sub_module' => 'application-agreement-received','name' => 'list-application-agreement-received','guard_name' => 'admin',],
            ['id' => 95,'module' => 'applications','sub_module' => 'application-agreement-received','name' => 'update-application-agreement-received','guard_name' => 'admin',],
            ['id' => 96,'module' => 'applications','sub_module' => 'application-agreement-received','name' => 'delete-application-agreement-received','guard_name' => 'admin',],
            ['id' => 97,'module' => 'applications','sub_module' => 'application-agreement-received','name' => 'view-application-agreement-received','guard_name' => 'admin',],
            ['id' => 98,'module' => 'applications','sub_module' => 'application-agreement-received','name' => 'export-application-agreement-received','guard_name' => 'admin',],
            ['id' => 99,'module' => 'applications','sub_module' => 'application-agreement-received','name' => 'not-interested-application-agreement-received','guard_name' => 'admin',],
            ['id' => 100,'module' => 'applications','sub_module' => 'application-agreement-signed','name' => 'list-application-agreement-signed','guard_name' => 'admin',],
            ['id' => 101,'module' => 'applications','sub_module' => 'application-agreement-signed','name' => 'update-application-agreement-signed','guard_name' => 'admin',],
            ['id' => 102,'module' => 'applications','sub_module' => 'application-agreement-signed','name' => 'delete-application-agreement-signed','guard_name' => 'admin',],
            ['id' => 103,'module' => 'applications','sub_module' => 'application-agreement-signed','name' => 'view-application-agreement-signed','guard_name' => 'admin',],
            ['id' => 104,'module' => 'applications','sub_module' => 'application-agreement-signed','name' => 'export-application-agreement-signed','guard_name' => 'admin',],
            ['id' => 105,'module' => 'applications','sub_module' => 'application-agreement-signed','name' => 'not-interested-application-agreement-signed','guard_name' => 'admin',],
            ['id' => 106,'module' => 'applications','sub_module' => 'application-rate-accepted','name' => 'list-application-rate-accepted','guard_name' => 'admin',],
            ['id' => 107,'module' => 'applications','sub_module' => 'application-rate-accepted','name' => 'update-application-rate-accepted','guard_name' => 'admin',],
            ['id' => 108,'module' => 'applications','sub_module' => 'application-rate-accepted','name' => 'delete-application-rate-accepted','guard_name' => 'admin',],
            ['id' => 109,'module' => 'applications','sub_module' => 'application-rate-accepted','name' => 'view-application-rate-accepted','guard_name' => 'admin',],
            ['id' => 110,'module' => 'applications','sub_module' => 'application-rate-accepted','name' => 'export-application-rate-accepted','guard_name' => 'admin',],
            ['id' => 111,'module' => 'applications','sub_module' => 'application-rate-decline','name' => 'list-application-rate-decline','guard_name' => 'admin',],
            ['id' => 112,'module' => 'applications','sub_module' => 'application-rate-decline','name' => 'update-application-rate-decline','guard_name' => 'admin',],
            ['id' => 113,'module' => 'applications','sub_module' => 'application-rate-decline','name' => 'delete-application-rate-decline','guard_name' => 'admin',],
            ['id' => 114,'module' => 'applications','sub_module' => 'application-rate-decline','name' => 'view-application-rate-decline','guard_name' => 'admin',],
            ['id' => 115,'module' => 'applications','sub_module' => 'application-rate-decline','name' => 'export-application-rate-decline','guard_name' => 'admin',],
            ['id' => 116,'module' => 'transactions','sub_module' => 'all-transaction','name' => 'list-all-transaction','guard_name' => 'admin',],
            ['id' => 117,'module' => 'transactions','sub_module' => 'all-transaction','name' => 'update-all-transaction','guard_name' => 'admin',],
            ['id' => 118,'module' => 'transactions','sub_module' => 'all-transaction','name' => 'delete-all-transaction','guard_name' => 'admin',],
            ['id' => 119,'module' => 'transactions','sub_module' => 'all-transaction','name' => 'view-all-transaction','guard_name' => 'admin',],
            ['id' => 120,'module' => 'transactions','sub_module' => 'all-transaction','name' => 'export-all-transaction','guard_name' => 'admin',],
            ['id' => 121,'module' => 'transactions','sub_module' => 'crypto-transaction','name' => 'list-crypto-transaction','guard_name' => 'admin',],
            ['id' => 122,'module' => 'transactions','sub_module' => 'crypto-transaction','name' => 'update-crypto-transaction','guard_name' => 'admin',],
            ['id' => 123,'module' => 'transactions','sub_module' => 'crypto-transaction','name' => 'view-crypto-transaction','guard_name' => 'admin',],
            ['id' => 124,'module' => 'transactions','sub_module' => 'crypto-transaction','name' => 'export-crypto-transaction','guard_name' => 'admin',],
            ['id' => 125,'module' => 'transactions','sub_module' => 'refund-transaction','name' => 'list-refund-transaction','guard_name' => 'admin',],
            ['id' => 126,'module' => 'transactions','sub_module' => 'refund-transaction','name' => 'update-refund-transaction','guard_name' => 'admin',],
            ['id' => 127,'module' => 'transactions','sub_module' => 'refund-transaction','name' => 'view-refund-transaction','guard_name' => 'admin',],
            ['id' => 128,'module' => 'transactions','sub_module' => 'refund-transaction','name' => 'export-refund-transaction','guard_name' => 'admin',],
            ['id' => 129,'module' => 'transactions','sub_module' => 'chargeback-transaction','name' => 'list-chargeback-transaction','guard_name' => 'admin',],
            ['id' => 130,'module' => 'transactions','sub_module' => 'chargeback-transaction','name' => 'update-chargeback-transaction','guard_name' => 'admin',],
            ['id' => 131,'module' => 'transactions','sub_module' => 'chargeback-transaction','name' => 'view-chargeback-transaction','guard_name' => 'admin',],
            ['id' => 132,'module' => 'transactions','sub_module' => 'chargeback-transaction','name' => 'export-chargeback-transaction','guard_name' => 'admin',],
            ['id' => 133,'module' => 'transactions','sub_module' => 'retrival-transaction','name' => 'list-retrival-transaction','guard_name' => 'admin',],
            ['id' => 134,'module' => 'transactions','sub_module' => 'retrival-transaction','name' => 'update-retrival-transaction','guard_name' => 'admin',],
            ['id' => 135,'module' => 'transactions','sub_module' => 'retrival-transaction','name' => 'view-retrival-transaction','guard_name' => 'admin',],
            ['id' => 136,'module' => 'transactions','sub_module' => 'retrival-transaction','name' => 'export-retrival-transaction','guard_name' => 'admin',],
            ['id' => 137,'module' => 'transactions','sub_module' => 'suspicious-transaction','name' => 'list-suspicious-transaction','guard_name' => 'admin',],
            ['id' => 138,'module' => 'transactions','sub_module' => 'suspicious-transaction','name' => 'update-suspicious-transaction','guard_name' => 'admin',],
            ['id' => 139,'module' => 'transactions','sub_module' => 'suspicious-transaction','name' => 'view-suspicious-transaction','guard_name' => 'admin',],
            ['id' => 140,'module' => 'transactions','sub_module' => 'suspicious-transaction','name' => 'export-suspicious-transaction','guard_name' => 'admin',],
            ['id' => 141,'module' => 'transactions','sub_module' => 'declined-transaction','name' => 'list-declined-transaction','guard_name' => 'admin',],
            ['id' => 142,'module' => 'transactions','sub_module' => 'declined-transaction','name' => 'view-declined-transaction','guard_name' => 'admin',],
            ['id' => 143,'module' => 'transactions','sub_module' => 'declined-transaction','name' => 'export-declined-transaction','guard_name' => 'admin',],
            ['id' => 144,'module' => 'transactions','sub_module' => 'test-transaction','name' => 'list-test-transaction','guard_name' => 'admin',],
            ['id' => 145,'module' => 'transactions','sub_module' => 'test-transaction','name' => 'view-test-transaction','guard_name' => 'admin',],
            ['id' => 146,'module' => 'transactions','sub_module' => 'test-transaction','name' => 'export-test-transaction','guard_name' => 'admin',],
            ['id' => 147,'module' => 'transactions','sub_module' => 'suspicious-transaction','name' => 'remove-suspicious-transaction','guard_name' => 'admin',],
            ['id' => 148,'module' => 'summary-Report','sub_module' => 'transaction-summary-report','name' => 'list-transaction-summary-report','guard_name' => 'admin',],
            ['id' => 149,'module' => 'summary-Report','sub_module' => 'transaction-summary-report','name' => 'export-transaction-summary-report','guard_name' => 'admin',],
            ['id' => 150,'module' => 'summary-Report','sub_module' => 'auto-suspicious-report','name' => 'list-auto-suspicious-report','guard_name' => 'admin',],
            ['id' => 151,'module' => 'summary-Report','sub_module' => 'generated-payout-reports','name' => 'list-generated-payout-reports','guard_name' => 'admin',],
            ['id' => 152,'module' => 'summary-Report','sub_module' => 'generated-payout-reports','name' => 'form-generate-payout-reports','guard_name' => 'admin',],
            ['id' => 153,'module' => 'summary-Report','sub_module' => 'generated-payout-reports','name' => 'export-generated-payout-reports','guard_name' => 'admin',],
            ['id' => 154,'module' => 'summary-Report','sub_module' => 'generated-payout-reports','name' => 'delete-generated-payout-reports','guard_name' => 'admin',],
            ['id' => 155,'module' => 'summary-Report','sub_module' => 'generated-payout-reports','name' => 'update-generated-payout-reports','guard_name' => 'admin',],
            ['id' => 156,'module' => 'summary-Report','sub_module' => 'generated-payout-reports','name' => 'show-generated-payout-reports','guard_name' => 'admin',],
            ['id' => 157,'module' => 'summary-Report','sub_module' => 'generated-referral-partner-reports','name' => 'list-generated-referral-partner-reports','guard_name' => 'admin',],
            ['id' => 158,'module' => 'summary-Report','sub_module' => 'generated-referral-partner-reports','name' => 'form-generate-referral-partner-reports','guard_name' => 'admin',],
            ['id' => 159,'module' => 'summary-Report','sub_module' => 'generated-referral-partner-reports','name' => 'export-generated-referral-partner-reports','guard_name' => 'admin',],
            ['id' => 160,'module' => 'summary-Report','sub_module' => 'generated-referral-partner-reports','name' => 'delete-generated-referral-partner-reports','guard_name' => 'admin',],
            ['id' => 161,'module' => 'summary-Report','sub_module' => 'generated-referral-partner-reports','name' => 'update-generated-referral-partner-reports','guard_name' => 'admin',],
            ['id' => 162,'module' => 'summary-Report','sub_module' => 'generated-referral-partner-reports','name' => 'show-generated-referral-partner-reports','guard_name' => 'admin',],
            ['id' => 163,'module' => 'summary-Report','sub_module' => 'referral-partner-report','name' => 'list-referral-partner-report','guard_name' => 'admin',],
            ['id' => 164,'module' => 'ticket','sub_module' => 'ticket','name' => 'list-ticket','guard_name' => 'admin',],
            ['id' => 165,'module' => 'ticket','sub_module' => 'ticket','name' => 'update-ticket','guard_name' => 'admin',],
            ['id' => 166,'module' => 'ticket','sub_module' => 'ticket','name' => 'delete-ticket','guard_name' => 'admin',],
            ['id' => 167,'module' => 'ticket','sub_module' => 'ticket','name' => 'show-ticket','guard_name' => 'admin',],
            ['id' => 168,'module' => 'technical-Additional','sub_module' => 'ip-whitelist','name' => 'list-ip-whitelist','guard_name' => 'admin',],
            ['id' => 169,'module' => 'technical-Additional','sub_module' => 'ip-whitelist','name' => 'action-ip-whitelist','guard_name' => 'admin',],
            ['id' => 170,'module' => 'technical-Additional','sub_module' => 'iframe-generator','name' => 'iframe-generator','guard_name' => 'admin',],
            ['id' => 171,'module' => 'technical-Additional','sub_module' => 'session-data','name' => 'list-session-data','guard_name' => 'admin',],
            ['id' => 172,'module' => 'technical-Additional','sub_module' => 'session-data','name' => 'action-session-data','guard_name' => 'admin',],
            ['id' => 173,'module' => 'technical-Additional','sub_module' => 'required-fields','name' => 'list-required-fields','guard_name' => 'admin',],
            ['id' => 174,'module' => 'technical-Additional','sub_module' => 'required-fields','name' => 'create-required-fields','guard_name' => 'admin',],
            ['id' => 175,'module' => 'technical-Additional','sub_module' => 'required-fields','name' => 'update-required-fields','guard_name' => 'admin',],
            ['id' => 176,'module' => 'technical-Additional','sub_module' => 'required-fields','name' => 'delete-required-fields','guard_name' => 'admin',],
            ['id' => 177,'module' => 'technical-Additional','sub_module' => 'payout-schedule','name' => 'list-payout-schedule','guard_name' => 'admin',],
            ['id' => 178,'module' => 'technical-Additional','sub_module' => 'payout-schedule','name' => 'create-payout-schedule','guard_name' => 'admin',],
            ['id' => 179,'module' => 'technical-Additional','sub_module' => 'payout-schedule','name' => 'update-payout-schedule','guard_name' => 'admin',],
            ['id' => 180,'module' => 'technical-Additional','sub_module' => 'payout-schedule','name' => 'delete-payout-schedule','guard_name' => 'admin',],
            ['id' => 181,'module' => 'technical-Additional','sub_module' => 'industry-type','name' => 'list-industry-type','guard_name' => 'admin',],
            ['id' => 182,'module' => 'technical-Additional','sub_module' => 'industry-type','name' => 'create-industry-type','guard_name' => 'admin',],
            ['id' => 183,'module' => 'technical-Additional','sub_module' => 'industry-type','name' => 'update-industry-type','guard_name' => 'admin',],
            ['id' => 184,'module' => 'technical-Additional','sub_module' => 'industry-type','name' => 'delete-industry-type','guard_name' => 'admin',],
            ['id' => 185,'module' => 'technical-Additional','sub_module' => 'integration-preference','name' => 'list-integration-preference','guard_name' => 'admin',],
            ['id' => 186,'module' => 'technical-Additional','sub_module' => 'integration-preference','name' => 'create-integration-preference','guard_name' => 'admin',],
            ['id' => 187,'module' => 'technical-Additional','sub_module' => 'integration-preference','name' => 'update-integration-preference','guard_name' => 'admin',],
            ['id' => 188,'module' => 'technical-Additional','sub_module' => 'integration-preference','name' => 'delete-integration-preference','guard_name' => 'admin',],
            ['id' => 189,'module' => 'technical-Additional','sub_module' => 'admin-logs','name' => 'list-admin-logs','guard_name' => 'admin',],
            ['id' => 190,'module' => 'summary-Report','sub_module' => 'merchant-transaction-report','name' => 'list-merchant-transaction-report','guard_name' => 'admin',],
            ['id' => 191,'module' => 'summary-Report','sub_module' => 'merchant-transaction-report','name' => 'export-merchant-transaction-report','guard_name' => 'admin',],
            ['id' => 192,'module' => 'technical-Additional','sub_module' => 'mail-templates','name' => 'list-mail-templates','guard_name' => 'admin',],
            ['id' => 193,'module' => 'technical-Additional','sub_module' => 'mail-templates','name' => 'create-mail-templates','guard_name' => 'admin',],
            ['id' => 194,'module' => 'technical-Additional','sub_module' => 'mail-templates','name' => 'update-mail-templates','guard_name' => 'admin',],
            ['id' => 195,'module' => 'technical-Additional','sub_module' => 'mail-templates','name' => 'delete-mail-templates','guard_name' => 'admin',],
            ['id' => 196,'module' => 'summary-Report','sub_module' => 'summary-report','name' => 'summary-report','guard_name' => 'admin',],
            ['id' => 197,'module' => 'blocked-System','sub_module' => 'block-Card','name' => 'delete-block-card','guard_name' => 'admin',],
            ['id' => 198,'module' => 'blocked-System','sub_module' => 'block-Card','name' => 'view-blocked-system','guard_name' => 'admin',],
            ['id' => 199,'module' => 'cron-management','sub_module' => 'cron-management','name' => 'view-cron-management','guard_name' => 'admin',],
            ['id' => 200,'module' => 'transactions','sub_module' => 'company-name','name' => 'company-name','guard_name' => 'admin',],
            ['id' => 201,'module' => 'technical-Additional','sub_module' => 'mass-mid-switching','name' => 'mass-mid-switching','guard_name' => 'admin',],
            ['id' => 202,'module' => 'users','sub_module' => 'user wl rp','name' => 'view-wl-rp','guard_name' => 'admin',],
            ['id' => 203,'module' => 'users','sub_module' => 'user wl rp','name' => 'create-wl-rp','guard_name' => 'admin',],
            ['id' => 204,'module' => 'users','sub_module' => 'user wl rp','name' => 'update-wl-rp','guard_name' => 'admin',],
            ['id' => 205,'module' => 'users','sub_module' => 'user wl rp','name' => 'delete-wl-rp','guard_name' => 'admin',],
            ['id' => 206,'module' => 'users','sub_module' => 'user wl rp','name' => 'export-wl-rp','guard_name' => 'admin',],
            ['id' => 207,'module' => 'users','sub_module' => 'user wl rp','name' => 'wl-rp-merchant-management','guard_name' => 'admin',],
            ['id' => 208,'module' => 'users','sub_module' => 'user wl rp','name' => 'wl-rp-merchant-list','guard_name' => 'admin',],
            ['id' => 209,'module' => 'users','sub_module' => 'user wl rp','name' => 'wl-rp-merchant-create','guard_name' => 'admin',],
            ['id' => 210,'module' => 'transactions','sub_module' => 'pre arbitration transactions','name' => 'list-pre-arbitration','guard_name' => 'admin',],
            ['id' => 211,'module' => 'transactions','sub_module' => 'pre arbitration transactions','name' => 'view-pre-arbitration','guard_name' => 'admin',],
            ['id' => 212,'module' => 'transactions','sub_module' => 'pre arbitration transactions','name' => 'update-pre-arbitration','guard_name' => 'admin',],
            ['id' => 213,'module' => 'transactions','sub_module' => 'pre arbitration transactions','name' => 'export-pre-arbitration','guard_name' => 'admin',],
            ['id' => 214,'module' => 'users','sub_module' => 'user merchant','name' => 'view-merchant-stores','guard_name' => 'admin',],
        ];
        foreach($actions as $action) {
            $isexist = Permission::find($action['id']);
            if (!$isexist) {
                Permission::Create($action);
            }
        }
    }
}
